### ISSUE TITLE
Messenger share location missing

### ISSUE THREAD

**Issue by cvazouras** [NeonOrbit/MRVPatchManager#11]
Sharing location is missing on Messenger, and when another user shares their location it says "You have received a message but your version of Messenger doesn't support it. Update Messenger" (screenshot attached)

![Screenshot_2024-02-13-11-56-02-399_com.facebook.orca-edit.jpg](https://github.com/NeonOrbit/MRVPatchManager/assets/43879300/fb57ecc7-0c99-4b5a-b168-9a26cfec5c86)

**Comment by NeonOrbit** [comment]
Select the app you want to update, and click Patch. If a newer version is available, it will be downloaded automatically.

**Comment by cvazouras** [comment]
Great, thank you!
