### ISSUE TITLE
How to fix this 

### ISSUE THREAD

**Issue by Reepzvan25** [NeonOrbit/MRVPatchManager#14]
The previous one is uninstalled because I want to install a newer version but when you install the latest patched one it says update or cancel? How to fix this?

**Comment by NeonOrbit** [comment]
I'm not sure what you are talking about, please attach a screenshot.

**Comment by Reepzvan25** [comment]
Wait

**Comment by Reepzvan25** [comment]
See the screenshot below note: I don't have messenger app installed on my
phone.

**Comment by Reepzvan25** [comment]
And I can't install messenger from play store either

**Comment by Reepzvan25** [comment]
I able to fix it. By installing the patched one from your xda page the with
the latest update on may 20 then after that I uninstalled it manually
