### ISSUE TITLE
Toggle icon disappeared from new Messenger versions

### ISSUE THREAD

**Issue by Dat-Mobile** [NeonOrbit/MRVPatchManager#15]
Toggle icon disappeared from new Messenger versions

I'm using Oneplus 11, android 14, oxygenos 14
- ChatHeadEnabler 2.4.5
- MRVPatch Manager 2.3.1

**Comment by schonescofield** [comment]
I'm using Pixel 4XL, android 13
Toggle icon disappeared from new Messenger versions then from all Earlier versions too

**Comment by NeonOrbit** [comment]
[Fixed in v2.3.3](https://github.com/NeonOrbit/MRVPatchManager/releases/tag/v2.3.3)
