### ISSUE TITLE
CANNOT OPEN FACEBOOK AND MESSENGER ANY MORE

### ISSUE THREAD

**Issue by SilverCrow97** [NeonOrbit/MRVPatchManager#2]
I don't know why but i installed the apps from the play store after doing the process and they didint Open.

**Comment by NeonOrbit** [comment]
Why would you install from the playstore?

**Comment by AgentDZ** [comment]
Hey , i would like to inform you that other servers are down only one that works is apkcombo and you need to change it manually just in case someone needs and answer.

**Comment by NeonOrbit** [comment]
All servers are working fine
