### ISSUE TITLE
Can't enable 'Mask package name'

### ISSUE THREAD

**Issue by SunnyLeu** [NeonOrbit/MRVPatchManager#3]
Messenger on my phone can't be uninstalled, but I can't enable 'Mask package name', it's grayed out.
![image](https://github.com/NeonOrbit/MRVPatchManager/assets/51817348/af94f171-8d3e-4440-88fd-01efcd089c0b)

**Comment by NeonOrbit** [comment]
Messenger is removal on all devices. This option is for those who can't uninstall other fb apps (Facebook, Facebook Lite etc).

**Comment by SunnyLeu** [comment]
> Messenger is removable on all devices. This option is for those who can't uninstall other fb apps (Facebook, Facebook Lite etc).

No, in fact, on ZenFone 10, Messenger is pre-installed on `/product/app/` folder, and can't be completed uninstall.

**Comment by NeonOrbit** [comment]
Have you tried this adb command?
`adb shell pm uninstall -k --user 0 com.facebook.orca`

**Comment by SunnyLeu** [comment]
> Have you tried this adb command? `adb shell pm uninstall -k --user 0 com.facebook.orca`

Yes, but the `INSTALL_FAILED_UPDATE_INCOMPATIBLE` message still occurs.

**Comment by NeonOrbit** [comment]
Changing package name for a messy app like Messenger is problematic, it'll most likely fail (or crash occasionally). I'll see what I can do, but can't guarantee anything.

**Comment by SunnyLeu** [comment]
> Changing package name for a messy app like Messenger is problematic, it'll most likely fail (or crash occasionally). I'll see what I can do, but can't guarantee anything.

Ok, I appreciate that.

**Comment by NeonOrbit** [comment]
@SunnyLeu Could you test this one? (I tried to make it as stable as possible)
[Messenger-v426.apk](https://github.com/NeonOrbit/Files/releases/download/mrv-tmp/msg416-mrv.apk)

**Comment by SunnyLeu** [comment]
> @SunnyLeu Could you test this one? (I tried to make it as stable as possible) [Messenger-v426.apk](https://github.com/NeonOrbit/Files/releases/download/mrv-tmp/msg416-mrv.apk)

Thank you so much for your assistance with the file. Everything seems to be fine now, and I really appreciate your help.

However, I noticed a small issue with opening the link to Facebook.com. It doesn't seem to work, but interestingly, the link opens successfully when I use the original version of the program. Apart from that, I thoroughly tested several functions like calling, stickers, notifications, notes, taking/editing photos, and opening other links (excluding Facebook.com), and I'm happy to report that they all work perfectly. Thank you once again for your support.

**Comment by NeonOrbit** [comment]
> I did encounter a small issue with opening the link to Facebook.com. It doesn't seem to work

That's expected. As I mentioned before, changing the package is a messy solution. I'm surprised that it's even working. 
In order to install it without conflicting with existing apps, I had to prevent all kinds of connections between Messenger and any other Facebook apps. 
Note that, "Mask package" option should be the last resort, and you'll have to deal with some limitations if you choose it.

**Comment by NeonOrbit** [comment]
Try this one too, it's latest version (fixed some bugs too).
[Messenger-v418.apk](https://github.com/NeonOrbit/Files/releases/download/mrv-tmp/msg418-mrv.apk)

**Comment by SunnyLeu** [comment]
I found that I can't open this link in app 

> Try this one too, it's latest version (fixed some bugs too). [Messenger-v418.apk](https://github.com/NeonOrbit/Files/releases/download/mrv-tmp/msg418-mrv.apk)

I can't install this, is the signature original?

**Comment by SunnyLeu** [comment]
And I found out that I can't open `forum.gamer.com.tw` link in app [`巴哈姆特 (https://play.google.com/store/apps/details?id=tw.com.gamer.android.activecenter)`](https://play.google.com/store/apps/details?id=tw.com.gamer.android.activecenter).  App `巴哈姆特` contains links below: `haha.gamer.com.tw`, `gnn.gamer.com.tw`, `api.gamer.com.tw`, `guild.gamer.com.tw`, `home.gamer.com.tw`, `forum.gamer.com.tw`, `wall.gamer.com.tw`, `m.gamer.com.tw`, and also unable to open `twitter.com` link in Twitter app, it shows 'Open in Chrome' in Messenger internel browser menu instead of 'Open in 巴哈姆特' or 'Open on Twitter'.

**Comment by NeonOrbit** [comment]
> I can't install this, is the signature original?

Sorry, I signed it with a different signature, here is the corrected version.
[Messenger-v418.apk](https://github.com/NeonOrbit/Files/releases/download/mrv-tmp/msg418-mrv.apk)

> I found out that I can't open `forum.gamer.com.tw` link in app

That's not relevant to Messenger in any way (even if it works with original Messenger), it's up to the system or the target app. 
Nevertheless, It shows 'Open in Twitter' and 'Open in 巴哈姆特' for both apps in my device. I don't know why it's not working on your phone, are you using a mod version of twitter too?
Anyway, there's a solution for that. If links are not opening in a particular app, apply this adb command with that app's package name. These will enable   'Open in Facebook' or 'Open in Twitter' etc.
For twitter: `adb shell pm set-app-links --package com.facebook.katana 1 all`
For twitter: `adb shell pm set-app-links --package com.twitter.android 1 all`
For 巴哈姆特: `adb shell pm set-app-links --package tw.com.gamer.android.activecenter 1 all`

**Comment by SunnyLeu** [comment]
Ok, I'll try, thanks for your help.

**Comment by NeonOrbit** [comment]
Added in the latest [release](https://github.com/NeonOrbit/MRVPatchManager/releases/latest)
